# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

sudo: required

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get -y update
  - sudo apt-get -y install libudunits2-dev libgdal-dev libgeos-dev libproj-dev

after_success:
  - Rscript -e 'covr::codecov()'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  keep_history: true
  local_dir: docs
  on:
    branch: master
